import pandas as pd
from flask_sqlalchemy import SQLAlchemy

from flask import Flask



app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'mssql+pyodbc://HARRISONS-THINK/LendApp'

db = SQLAlchemy(app)
SQLALCHEMY_TRACK_MODIFICATIONS = False

from sqlalchemy import create_engine, false

Server = ''
Database = ''
Driver = ''
Database_Con = f'mssql://@{Server}/{Database}?driver={Driver}'

engine = create_engine(Database_Con)
conn = engine.connect()


class Input(db.Model):
    UseScoring = db.Column(db.Boolean)
    Premium = db.Column(db.Float)
    AdditionalPremium = db.Column(db.Float)
    ProductVersion = db.Column(db.Integer)
    ScoringOn = db.Column(db.Boolean)
    ScoringStartDate = db.Column(db.DateTime, nullable=True)
    DateFrom = db.Column(db.DateTime)
    InsSum = db.Column(db.Float)
    Comission = db.Column(db.Float)
    ScoringComission = db.Column(db.Float)
    PolicyId = db.Column(db.String)
    PolicyNumber = db.Column(db.String)
    PrevPolicyId = db.Column(db.String)
    PrevPolicyNumber = db.Column(db.String)
    InsurerClientType = db.Column(db.Integer)
    InsurerBirthDate = db.Column(db.DateTime)
    InsurerDocumentType = db.Column(db.Integer)
    InsurerGender = db.Column(db.Integer)
    InsurerTitle = db.Column(db.String)
    InsurerPhone = db.Column(db.String)
    DriverMinAge = db.Column(db.Integer)
    SellerIKP = db.Column(db.String)
    AgentIKP = db.Column(db.String)
    VIN = db.Column(db.String)
    EnginePower = db.Column(db.Float)
    IssueYear = db.Column(db.Integer)
    TSCategory = db.Column(db.Integer)
    RegNumber = db.Column(db.String)
    BodyNumber = db.Column(db.String, nullable=True)  #
    ChassisNumber = db.Column(db.Integer, nullable=True)  #
    CoefKM = db.Column(db.Float)
    CoefKP = db.Column(db.Float)
    IsTaxi = db.Column(db.Boolean)
    CoefKO = db.Column(db.Float)
    CoefKBM = db.Column(db.Float)
    CoefKVC = db.Column(db.Float)
    CoefKT = db.Column(db.Float)
    BaseRate = db.Column(db.Float)
    CoefKN = db.Column(db.Float)
    CoefKPR = db.Column(db.Float)
    SeatsNumberTo16 = db.Column(db.Boolean)
    MaxWeightTo16 = db.Column(db.Boolean)
    CoefKS = db.Column(db.Float)
    IsForeignCountry = db.Column(db.Boolean)
    OwnerKLADRCode = db.Column(db.String)
    FIASGroup = db.Column(db.String)
    InsuranceTerm = db.Column(db.Integer)
    IsProlongation = db.Column(db.Boolean)
    SavingHour = db.Column(db.Integer)
    DateStartAndSavingDateDiff = db.Column(db.Integer)
    IsElectronic = db.Column(db.Boolean)
    DriverMinExperience = db.Column(db.Integer)
    CurrentSegment = db.Column(db.String)
    PredictSegment = db.Column(db.String)
    TSBrandId = db.Column(db.Integer)
    TSBrandName = db.Column(db.String)
    TSBrandRsaCode = db.Column(db.String)
    TSModelId = db.Column(db.Integer)
    TSModelName = db.Column(db.String)
    TSModelRsaCode = db.Column(db.String)
    BKIScore = db.Column(db.JSON, nullable=True)
    PTSSeries = db.Column(db.String)
    PTSNumber = db.Column(db.String)
    DriverUnlimit = db.Column(db.Boolean)
    AvtoKodJSON = db.Column(db.JSON)
    BKIJSON = db.Column(db.JSON, nullable=True)
    IsAdditionalAgreement = db.Column(db.Boolean)
    AgentType = db.Column(db.Integer)
    FilialCode = db.Column(db.String)
    FilialName = db.Column(db.String)
    OwnerRegionName = db.Column(db.String)
    IsToxic = db.Column(db.Boolean)
    IsMSK = db.Column(db.Boolean)
    IsEGARANT = db.Column(db.Boolean)
    IsEOSAGO = db.Column(db.Boolean)
    IsSold = db.Column(db.Boolean)
    Score = db.Column(db.Float)
    SegmentMessage = db.Column(db.String, nullable=True)
    OwnerClientType = db.Column(db.Integer)
    TaxiAvtokod = db.Column(db.Integer)
    DriversList = db.Column(db.JSON)
    CoefComission = db.Column(db.Integer)


class Output(db.Model):
    UseScoring = db.Column(db.Boolean)
    Premium = db.Column(db.Float)
    AdditionalPremium = db.Column(db.Float)
    ProductVersion = db.Column(db.Integer)
    ScoringOn = db.Column(db.Boolean)
    ScoringStartDate = db.Column(db.DateTime, nullable=True)
    DateFrom = db.Column(db.DateTime)
    InsSum = db.Column(db.Float)
    Comission = db.Column(db.Float)
    ScoringComission = db.Column(db.Float)
    PolicyId = db.Column(db.String)
    PolicyNumber = db.Column(db.String)
    PrevPolicyId = db.Column(db.String)
    PrevPolicyNumber = db.Column(db.String)
    InsurerClientType = db.Column(db.Integer)
    InsurerBirthDate = db.Column(db.DateTime)
    InsurerDocumentType = db.Column(db.Integer)
    InsurerGender = db.Column(db.Integer)
    InsurerTitle = db.Column(db.String)
    InsurerPhone = db.Column(db.String)
    DriverMinAge = db.Column(db.Integer)
    SellerIKP = db.Column(db.String)
    AgentIKP = db.Column(db.String)
    VIN = db.Column(db.String)
    EnginePower = db.Column(db.Float)
    IssueYear = db.Column(db.Integer)
    TSCategory = db.Column(db.Integer)
    RegNumber = db.Column(db.String)
    BodyNumber = db.Column(db.String, nullable=True)  #
    ChassisNumber = db.Column(db.Integer, nullable=True)  #
    CoefKM = db.Column(db.Float)
    CoefKP = db.Column(db.Float)
    IsTaxi = db.Column(db.Boolean)
    CoefKO = db.Column(db.Float)
    CoefKBM = db.Column(db.Float)
    CoefKVC = db.Column(db.Float)
    CoefKT = db.Column(db.Float)
    BaseRate = db.Column(db.Float)
    CoefKN = db.Column(db.Float)
    CoefKPR = db.Column(db.Float)
    SeatsNumberTo16 = db.Column(db.Boolean)
    MaxWeightTo16 = db.Column(db.Boolean)
    CoefKS = db.Column(db.Float)
    IsForeignCountry = db.Column(db.Boolean)
    OwnerKLADRCode = db.Column(db.String)
    FIASGroup = db.Column(db.String)
    InsuranceTerm = db.Column(db.Integer)
    IsProlongation = db.Column(db.Boolean)
    SavingHour = db.Column(db.Integer)
    DateStartAndSavingDateDiff = db.Column(db.Integer)
    IsElectronic = db.Column(db.Boolean)
    DriverMinExperience = db.Column(db.Integer)
    CurrentSegment = db.Column(db.String)
    PredictSegment = db.Column(db.String)
    TSBrandId = db.Column(db.Integer)
    TSBrandName = db.Column(db.String)
    TSBrandRsaCode = db.Column(db.String)
    TSModelId = db.Column(db.Integer)
    TSModelName = db.Column(db.String)
    TSModelRsaCode = db.Column(db.String)
    BKIScore = db.Column(db.JSON, nullable=True)
    PTSSeries = db.Column(db.String)
    PTSNumber = db.Column(db.String)
    DriverUnlimit = db.Column(db.Boolean)
    AvtoKodJSON = db.Column(db.JSON)
    BKIJSON = db.Column(db.JSON, nullable=True)
    IsAdditionalAgreement = db.Column(db.Boolean)
    AgentType = db.Column(db.Integer)
    FilialCode = db.Column(db.String)
    FilialName = db.Column(db.String)
    OwnerRegionName = db.Column(db.String)
    IsToxic = db.Column(db.Boolean)
    IsMSK = db.Column(db.Boolean)
    IsEGARANT = db.Column(db.Boolean)
    IsEOSAGO = db.Column(db.Boolean)
    IsSold = db.Column(db.Boolean)
    Score = db.Column(db.Float)
    SegmentMessage = db.Column(db.String, nullable=True)
    OwnerClientType = db.Column(db.Integer)
    TaxiAvtokod = db.Column(db.Integer)
    DriversList = db.Column(db.JSON)
    InsurancePeriodList = db.Column(db.JSON)
    now_date = db.Column(db.DateTime)
    Autocod_year = db.Column(db.Integer)
    Autocod_EnginePower = db.Column(db.Float)


if __name__ == '__main__':
    app.run(debug=True)
